name: Osteria Scarpetta Alla Fraccia
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
markdown_ext:  markdown,mkdown,mkdn,mkd,md
markdown: redcarpet
pygments: false
